### ISSUE TITLE
在 User profile template 中顯示細節

### ISSUE THREAD

**Issue by pellaeon** [sitcon-tw/roboconf#64]
`user/templates/profile.html`

我覺得應該要新增一個權限： `view_others_detail` ，可以檢視其他使用者細部、隱私的資料，例如性別、出發地等，可以開給行政組。若沒有這個權限，則只顯示基本的資料（目前顯示的東西）。

否則目前行政組只能依賴 fancy profile edit 來檢視資料。

@shadowlyc 覺得如何？

**Comment by shadowlyc** [comment]
我覺得可以，基本上這個權限也只要開給我跟姿姿即可，麻煩了！

**Comment by pcchou** [comment]
Already implemented in 6e8b4adef93ddc44afee5f8843be686906e3645c :beers:
