### ISSUE TITLE
Migrate to Django 1.9 and Python 3

### ISSUE THREAD

**Issue by pellaeon** [sitcon-tw/roboconf#66]
cfp-dev 和 master branch 都要 migrate 哦

**Comment by wdv4758h** [comment]
master branch 的 code 已經用 2to3 轉完然後手修了一些問題，可以在 branch [python3](https://github.com/sitcon-tw/staff.sitcon.org/tree/python3) 看到，雖然目前 testing 不夠完整，但是可以先在 local 端切過去跑來試試

**Comment by pcchou** [comment]
@wdv4758h 太棒了！

我沒注意到 python3 branch 上面的事情XD
我是不是該把我在 master 的 commit 折進 python3 啊？

還是之後一起 merge

**Comment by wdv4758h** [comment]
昨天才 push 上去的 XD

目前是單一一個 commit，等覺得 OK 後 master 直接 pick 過去或是 rebase 後 merge 應該就好了

**Comment by pcchou** [comment]
@wdv4758h 我剛剛 rebase 後試了一下，我自己覺得是沒什麼問題，
再等一陣子進一步測試吧 :laughing:
