### ISSUE TITLE
匯出 vcard nickname 會是空的

### ISSUE THREAD

**Issue by denny0223** [sitcon-tw/roboconf#73]
vcard 檔案結果大致為

```
BEGIN:VCARD
VERSION:4.0

FN:
NICKNAME:
ORG:COSCUP 2016 
TITLE:總召
PHOTO;VALUE=uri:https://secure.gravatar.com/avatar/xxxxx
TEL;TYPE=cell:09XXXXXXXX
EMAIL:XXXXXXXX@gmail.com
END:VCARD
```

關鍵 commit 應該是在這一筆 586cc725a9cd63ee8566c7cd1a0528d590586b66

**Comment by rschiang** [comment]
@pcchou 剛剛看了一下是 586cc725a9cd63ee8566c7cd1a0528d590586b66，`name` 被拔掉了變成 `username` 所以找不到變數
問一下為什麼會把 `id` 跟 `name` 改掉呢？原本的寫法是為了避免 expose 內部 ID，然後因為有人常常不寫名字所以 `name` 這個 `@property` 會自動 fallback 姓名，算是 helper function。

**Comment by rschiang** [comment]
如果沒有特別原因的話我可以幫忙 refactor 這段～

**Comment by rschiang** [comment]
Fixed in ea54abf32417934a97951f3245a2d38626307eef.
